package in.hauu.gui;

import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class DiaryExporter extends JFrame {
    private JButton поехалиКнопка;
    private JComboBox serviceSelector;
    private JTextField loginField;
    private JPasswordField passwordField;
    private JProgressBar pagesBar;
    private JProgressBar commentsBar;
    private JPanel panel;

    public DiaryExporter() throws HeadlessException {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 600);
        setTitle("(dark) Diary exporter, by hauu, v.1.0");
        setContentPane(panel);
        pack();
        setVisible(true);
    }

    public void moveCommentBar(int current, int max) {
        this.commentsBar.setValue(current);
        this.commentsBar.setMaximum(max);
    }

    public void movePostBar(int current, int max) {
        this.pagesBar.setValue(current);
        this.pagesBar.setMaximum(max);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(10, 7, new Insets(10, 10, 10, 10), -1, -1));
        panel.setEnabled(true);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("Выберите систему:");
        panel.add(
                label1,
                new com.intellij.uiDesigner.core.GridConstraints(
                        1,
                        1,
                        1,
                        2,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        1,
                        false
                )
        );
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(
                spacer1,
                new com.intellij.uiDesigner.core.GridConstraints(
                        1,
                        0,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        1,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        final JLabel label2 = new JLabel();
        label2.setText("Login");
        panel.add(
                label2,
                new com.intellij.uiDesigner.core.GridConstraints(
                        2,
                        1,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        1,
                        false
                )
        );
        final JLabel label3 = new JLabel();
        label3.setText("Password");
        panel.add(
                label3,
                new com.intellij.uiDesigner.core.GridConstraints(
                        3,
                        1,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        1,
                        false
                )
        );
        loginField = new JTextField();
        panel.add(
                loginField,
                new com.intellij.uiDesigner.core.GridConstraints(
                        2,
                        2,
                        1,
                        3,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        new Dimension(150, -1),
                        null,
                        0,
                        false
                )
        );
        passwordField = new JPasswordField();
        passwordField.setText("");
        panel.add(
                passwordField,
                new com.intellij.uiDesigner.core.GridConstraints(
                        3,
                        2,
                        1,
                        3,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        new Dimension(150, -1),
                        null,
                        0,
                        false
                )
        );
        serviceSelector = new JComboBox();
        serviceSelector.setEditable(true);
        serviceSelector.setEnabled(false);
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("DarkDiary");
        serviceSelector.setModel(defaultComboBoxModel1);
        panel.add(
                serviceSelector,
                new com.intellij.uiDesigner.core.GridConstraints(
                        1,
                        3,
                        1,
                        2,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(
                spacer2,
                new com.intellij.uiDesigner.core.GridConstraints(
                        1,
                        5,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        1,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        pagesBar = new JProgressBar();
        panel.add(
                pagesBar,
                new com.intellij.uiDesigner.core.GridConstraints(
                        6,
                        4,
                        1,
                        2,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        commentsBar = new JProgressBar();
        panel.add(
                commentsBar,
                new com.intellij.uiDesigner.core.GridConstraints(
                        7,
                        4,
                        1,
                        2,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        final com.intellij.uiDesigner.core.Spacer spacer3 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(
                spacer3,
                new com.intellij.uiDesigner.core.GridConstraints(
                        6,
                        6,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        1,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        final com.intellij.uiDesigner.core.Spacer spacer4 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(
                spacer4,
                new com.intellij.uiDesigner.core.GridConstraints(
                        7,
                        6,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        1,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        final JLabel label4 = new JLabel();
        label4.setText("Страницы");
        panel.add(
                label4,
                new com.intellij.uiDesigner.core.GridConstraints(
                        6,
                        1,
                        1,
                        3,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        1,
                        false
                )
        );
        final JLabel label5 = new JLabel();
        label5.setText("Комменты");
        panel.add(
                label5,
                new com.intellij.uiDesigner.core.GridConstraints(
                        7,
                        1,
                        1,
                        3,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_NONE,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        1,
                        false
                )
        );
        final com.intellij.uiDesigner.core.Spacer spacer5 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(
                spacer5,
                new com.intellij.uiDesigner.core.GridConstraints(
                        8,
                        1,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        поехалиКнопка = new JButton();
        поехалиКнопка.setText("Поехали!");
        panel.add(
                поехалиКнопка,
                new com.intellij.uiDesigner.core.GridConstraints(
                        4,
                        1,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                        null,
                        null,
                        null,
                        1,
                        false
                )
        );
        final com.intellij.uiDesigner.core.Spacer spacer6 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(
                spacer6,
                new com.intellij.uiDesigner.core.GridConstraints(
                        5,
                        1,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        final com.intellij.uiDesigner.core.Spacer spacer7 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(
                spacer7,
                new com.intellij.uiDesigner.core.GridConstraints(
                        0,
                        0,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
        final com.intellij.uiDesigner.core.Spacer spacer8 = new com.intellij.uiDesigner.core.Spacer();
        panel.add(
                spacer8,
                new com.intellij.uiDesigner.core.GridConstraints(
                        9,
                        1,
                        1,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                        com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL,
                        1,
                        com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                        null,
                        null,
                        null,
                        0,
                        false
                )
        );
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
